FROM mongo:4.2.3

COPY ./scripts/mongo/schema/schema.js /docker-entrypoint-initdb.d/01-schema.js
COPY ./scripts/mongo/schema/init.js /docker-entrypoint-initdb.d/02-init.js

COPY ./scripts/mongo /scripts
